# Use the activation bytes generated by this project.
# Note if `ACTIVATION_BYTES` are supplied, `ACTIVATION_BYTES_FILE` is ignored.
ACTIVATION_BYTES_FILE="./config/activation_bytes.txt"

# Or, if you have your activation bytes from another project, supply them here
# Note if `ACTIVATION_BYTES` are supplied, `ACTIVATION_BYTES_FILE` is ignored.
ACTIVATION_BYTES=""

# Where are your AAX files saved?
AAX_DIR="~/audible/aax"

# Where do you want the cover art saved?
COVER_ART_DIR="~/audible/cover_art"

# Where do you want the audiobook audio files saved?  The converted AAX files
# will have the extension `mkv`.
MKV_DIR="~/audible/mkv"

# Set this to any value, such as `yes` to rename the cover art images
# and mkv files to have the format "Artist - Title", e.g.:
# Charles Darwin - The Voyage of the Beagle (Unabridged).mkv
RENAME=""
